config/routes.rb
Rails.application.routes.draw do
  #ユーザ用
  devise_for :users,  skip: [:passwords],  controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  
  #管理者用
  devise_for :admins, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: "public/homes#top"
  get "/about" => "public/homes#about"
  get "/admin" => "admin/homes#top"
  
  
  scope module: :public do
    get '/search', to: 'searches#search'
    resources :articles do
      resources :article_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :favorites, only: [:index]
    resources :users do
      member do
        get 'unsubscribe'
        patch 'withdrawal'
      end
      resource :relationships, only: [:create, :destroy]
      get '/followings' => 'relationships#followings', as: 'followings'
      get '/followers' => 'relationships#followers', as: 'followers'
      get '/timeline' => 'relationships#timeline'
    end
  end
  
   namespace :admin do
     get '/search', to: 'searches#search'
     resources :articles, only: [:index, :show, :edit, :update, :destroy ] do
       resources :article_comments, only: [:destroy]
     end
     resources :users do
      get '/followings' => 'relationships#followings', as: 'followings'
      get '/followers' => 'relationships#followers', as: 'followers'
    end
  end
end

app/models/article_comment.rb
class ArticleComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :article
  
  validates :comment, presence: true
end

app/controllers/admin/article_comments_controller.rb
class Admin::ArticleCommentsController < ApplicationController
  before_action :authenticate_admin!

  # コメント削除を行うアクション
  def destroy
    ArticleComment.find_by(id: params[:id], article_id: params[:article_id]).destroy
    redirect_to request.referer
  end

  private
  # ストロングパラメータを定義
  def article_comment_params
    params.require(:article_comment).permit(:comment)
  end
end

app/helpers/admin/article_comments_helper.rb
module Admin::ArticleCommentsHelper
end

app/views/admin/article_comments/_index.html.erb
<%# この部分は、特定の記事に関連するコメントを新しい順に表示する %>
<% article.article_comments.order(created_at: :desc).each do |article_comment| %>
<div class="card-body" style="border-bottom: 1px solid #dee2e6;">
  <div class="media">
    <%= link_to admin_user_path(article_comment.user) do %>
    <%= image_tag article_comment.user.get_image(50, 50), class: "bd-placeholder-img mr-3 rounded-circle", width: "64", height: "64" %>
    <% end %>
    <div class="media-body">
      <%= link_to article_comment.user.name, admin_user_path(article_comment.user), style: "color: black;" %>
      <span style="color: gray;"><%= article_comment.created_at.strftime('%Y/%m/%d %H:%M') %></span>
      <p class="mb-0 text-break"><%=safe_join(article_comment.comment.split("\n"),tag(:br))%></p>
    </div>
    <%= link_to "削除", admin_article_article_comment_path(article, article_comment), method: :delete,"data-confirm" => "本当に消しますか？", class:"btn btn-danger"%>
  </div>
</div>
<% end %>

 