config/routes.rb
Rails.application.routes.draw do
  #ユーザ用
  devise_for :users,  skip: [:passwords],  controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  
  #管理者用
  devise_for :admins, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: "public/homes#top"
  get "/about" => "public/homes#about"
  get "/admin" => "admin/homes#top"
  
  
  scope module: :public do
    get '/search', to: 'searches#search'
    resources :articles do
      resources :article_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :favorites, only: [:index]
    resources :users do
      member do
        get 'unsubscribe'
        patch 'withdrawal'
      end
      resource :relationships, only: [:create, :destroy]
      get '/followings' => 'relationships#followings', as: 'followings'
      get '/followers' => 'relationships#followers', as: 'followers'
      get '/timeline' => 'relationships#timeline'
    end
  end
  
   namespace :admin do
     get '/search', to: 'searches#search'
     resources :articles, only: [:index, :show, :edit, :update, :destroy ] do
       resources :article_comments, only: [:destroy]
     end
     resources :users do
      get '/followings' => 'relationships#followings', as: 'followings'
      get '/followers' => 'relationships#followers', as: 'followers'
    end
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin! 
  
  # topページを表示するアクション
  def top
    @articles = Article.order(created_at: :desc).page(params[:page]).per(10)
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<h5 class="text-center">投稿一覧</h5>
<div class="container">
  <div class="row">
    <div class="col">
      <div class="card col">
          <%# 各記事に対してループを実行%>
          <% @articles.each do |article| %>
        <div class="card-body" style="border-bottom: 1px solid #dee2e6;">
          <div class="media">
            <%= link_to admin_user_path(article.user.id) do %>
            <%= image_tag article.user.get_image(64, 64), class: "bd-placeholder-img mr-3 rounded-circle", width: "64", height: "64" %>
            <% end %>
             <div class="media-body">
                <%= link_to article.user.name, admin_user_path(article.user.id), style: "color: black;" %>
                <span style="color: gray;"><%= article.created_at.strftime('%Y/%m/%d %H:%M') %></span>
                <p class="mb-0 text-break"><%= link_to article.title, admin_article_path(article.id), style: "color: black;" %></p>
                <span style="color: gray;">お気に入り数：<%= article.favorites.count %></span>
                <span style="color: gray;">コメント数: <%= article.article_comments.count %></span>
             </div>
          </div>
        </div>
      <% end %>
      </div>
      <%= paginate @articles %>
    </div>
  </div>
</div>