config/routes.rb
Rails.application.routes.draw do
  #ユーザ用
  devise_for :users,  skip: [:passwords],  controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  
  #管理者用
  devise_for :admins, skip: [:registrations, :passwords] , controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: "public/homes#top"
  get "/about" => "public/homes#about"
  get "/admin" => "admin/homes#top"
  
  
  scope module: :public do
    get '/search', to: 'searches#search'
    resources :articles do
      resources :article_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :favorites, only: [:index]
    resources :users do
      member do
        get 'unsubscribe'
        patch 'withdrawal'
      end
      resource :relationships, only: [:create, :destroy]
      get '/followings' => 'relationships#followings', as: 'followings'
      get '/followers' => 'relationships#followers', as: 'followers'
      get '/timeline' => 'relationships#timeline'
    end
  end
  
   namespace :admin do
     get '/search', to: 'searches#search'
     resources :articles, only: [:index, :show, :edit, :update, :destroy ] do
       resources :article_comments, only: [:destroy]
     end
     resources :users do
      get '/followings' => 'relationships#followings', as: 'followings'
      get '/followers' => 'relationships#followers', as: 'followers'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FootballDays</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/eaf8f4499d.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <header>
   <nav class="navbar navbar-expand-lg navbar-light" style="background-color: rgba(135, 148, 196, 0.15);">
    <a class="navbar-brand text-success" href="/">Football days</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
        <li class="nav-item active"style="margin-right: 20px;">
          <%= link_to user_path(current_user), method: :get, class:"nav-link active" do %>
          <i class="fa-solid fa-user"></i>My page
				  <% end %>
        </li>
        <li class="nav-item active"style="margin-right: 20px;">
          <%= link_to user_timeline_path(current_user), method: :get, class:"nav-link active" do %>
          <i class="fa-sharp fa-regular fa-clock"></i>タイムライン
				  <% end %>
        </li>
        <li class="nav-item active" style="margin-right: 20px;">
          <%= link_to  articles_path, class:"nav-link active" do%>
          <i class="fa-solid fa-list"></i>投稿一覧
          <% end %>
        </li>
        <li class="nav-item active" style="margin-right: 20px;">
          <%= link_to favorites_path, class:"nav-link active" do%>
          <i class="fa-solid fa-heart"></i>お気に入り
          <% end %>
        </li>
        <li class="nav-item active" style="margin-right: 20px;">
          <%= link_to destroy_user_session_path, method: :delete , class:"nav-link active" do%>
          <i class="fa-solid fa-right-from-bracket"></i>ログアウト
          <% end %>
        </li>
        <li class="nav-item active" style="margin-right: 20px;">
          <%= button_to new_article_path, method: :get, class:"nav-link active btn btn-primary text-white", form_class: "nav-link-button" do %>
          <i class="fa-sharp fa-solid fa-pen"></i>投稿する
          <% end %>
        </li>
        <% elsif admin_signed_in? %>
        <li class="nav-item active" style="margin-right: 20px;">
          <%= link_to "ユーザ一覧", admin_users_path,class:"nav-link active" %>
        </li>
        <li class="nav-item active" style="margin-right: 20px;">
          <%= link_to "投稿一覧",  admin_articles_path, class:"nav-link active" %>
        </li>
        <li class="nav-item active" style="margin-right: 20px;">
          <%= link_to "ログアウト",  destroy_admin_session_path, method: :delete , class:"nav-link active" %>
        </li>
        <% else %>
        <li class="nav-item active" style="margin-right: 20px;">
          <%= link_to about_path, class:"nav-link active" do %>
          <i class="fa-solid fa-futbol"></i>About
          <% end %>
        </li>
        <li class="nav-item active" style="margin-right: 20px;">
          <%= link_to articles_path, class:"nav-link active" do %>
          <i class="fa-sharp fa-solid fa-indent"></i>投稿一覧
          <% end %>
        </li>
        <li class="nav-item active" style="margin-right: 20px;">
          <%= link_to new_user_registration_path, class:"nav-link active" do %>
          <i class="fa-solid fa-user-plus"></i>新規登録
          <% end %>
        </li>
        <li class="nav-item active" style="margin-right: 20px;">
          <%= link_to new_user_session_path, class:"nav-link active" do %>
          <i class="fa-solid fa-right-to-bracket"></i>ログイン
          <% end %>
        </li>
        <li class="nav-item active" style="margin-right: 20px;">
          <%= link_to users_guest_sign_in_path, class: "nav-link active sign_in", method: :post do %>
          <i class="fa-sharp fa-solid fa-door-open"></i>ゲストログイン（閲覧用）
          <% end %>
        </li>
        <% end %>
      </ul>
      <!-- ナビゲーションバーの右側に要素を配置 -->
      <div class="form-inline my-2 my-lg-0 active">
        <% if admin_signed_in? %>
          <%= render 'admin/searches/form' %>
        <% else %>
          <%= render 'public/searches/form' %>
        <% end %>
      </div>
    </div>
   </nav>
  </header>
  <main class="min-vh-100">
     <%= yield %>
  </main>
   <footer class="bg-light py-1">
      <div class="container text-center">
        <%= link_to "Football days", root_path, style: "color: green;" %></p>
      </div>
   </footer>
  </body>
</html>